"""Scenario(s) transpiled from an OpenSCENARIO DSL source.

Source: /home/user/autoware_lanelet2_to_opendrive/examples/osc_transpiled_intersection_passing/intersection_passing.osc

Generated by autoware_carla_scenario.openscenario_dsl_frontend.
Edit freely — this file is plain, readable scenario code.
"""

from __future__ import annotations

import carla

from autoware_carla_scenario import (
    AndCondition,
    BaseScenario,
    ComparisonRule,
    EGO_ROLE_NAME,
    EgoConfig,
    ElapsedTimeCondition,
    EntityLanePositionCondition,
    GroundProjectionConfig,
    Lanelet2Pose,
    SequentialCondition,
    SpeedCondition,
    StickyCondition,
    TimeoutCondition,
    TrafficLightTarget,
    TrafficSignalAction,
    to_opendrive,
)

from .configs import IntersectionPassingConfig


class IntersectionPassingScenario(BaseScenario):
    """Transpiled scenario 'intersection_passing'."""

    def __init__(
        self,
        ego_config: EgoConfig,
        spawn_pose: Lanelet2Pose,
        config: IntersectionPassingConfig | None = None,
        ground_projection: GroundProjectionConfig | None = None,
    ) -> None:
        super().__init__(
            ego_config,
            spawn_pose=spawn_pose,
            ground_projection=ground_projection,
        )
        self._config = config or IntersectionPassingConfig()

    def setup(self) -> None:
        # Snap the ego spawn pose to the CARLA road surface.
        self._setup_ego_spawn()

        # Actions (serial order preserved via trigger conditions).
        self.register_pre_tick(
            TrafficSignalAction(
                state=carla.TrafficLightState.Green,
                lanelet2_traffic_light_ids=TrafficLightTarget.ALL,
                label="set_traffic_lights_green",
            )
        )

        # Pass conditions.
        self.register_pass_condition(
            SequentialCondition(
                [
                    StickyCondition(
                        EntityLanePositionCondition(
                            entity_name=EGO_ROLE_NAME,
                            road_id=to_opendrive(
                                Lanelet2Pose(lanelet_id=460, s=0.0)
                            ).road_id,
                            label="ego_reach_lane_460",
                        )
                    ),
                    StickyCondition(
                        EntityLanePositionCondition(
                            entity_name=EGO_ROLE_NAME,
                            road_id=to_opendrive(
                                Lanelet2Pose(lanelet_id=265, s=0.0)
                            ).road_id,
                            label="ego_reach_lane_265",
                        )
                    ),
                ],
                label="ordered_pass",
            )
        )

        # Fail conditions.
        self.register_fail_condition(
            TimeoutCondition(self._config.timeout_seconds, label="scenario_timeout")
        )
        self.register_fail_condition(
            AndCondition(
                [
                    ElapsedTimeCondition(3.0, label="ego_min_speed_delay"),
                    SpeedCondition(
                        entity_name=EGO_ROLE_NAME,
                        value=5.0 / 3.6,
                        rule=ComparisonRule.LESS_THAN,
                        label="ego_min_speed",
                    ),
                ]
            )
        )

    def is_done(self) -> bool:
        return False
