defaults:
  - _self_
  - server: localhost
  - ego: default
  - traffic_manager: default
  - scenario: intersection_passing/left_turn
  - map: nishishinjuku

server:
  host: localhost
  port: 2000

traffic_manager:
  port: 8100

map:
  name: ???
  xodr_path: null
  lanelet2_path: null
  no_3d_model_lanelet_ids: []

ego:
  vehicle_type: vehicle.mini.cooper
  initial_speed_kmh: 0.0
  spawn_lanelet_id: 242
  spawn_s: 25.0
  ground_projection_ray_distance_upper: 5.0
  ground_projection_ray_distance_lower: 10.0
