"""Session-scoped fixtures and shared test helpers for CARLA scenario tests.

Architecture
------------
All scenarios are registered into ``_queue`` at module import time (before
any fixture runs).  The single session-scoped ``carla_queue`` fixture starts
the CARLA server once, runs every registered scenario via
:meth:`ScenarioQueue.run_all`, and yields the queue.  Individual test fixtures
then simply call :meth:`ScenarioQueue.result_for` — CARLA is never restarted
between test cases.

Skipping
--------
``carla_queue`` is generated by :meth:`ScenarioQueue.as_fixture`, which
automatically skips when ``CARLA_UE5_EXECUTABLE`` is not set or when the
CARLA session cannot be established.
"""

from __future__ import annotations

from typing import Optional

import carla as _carla

from autoware_carla_scenario import (
    BaseCondition,
    BaseScenario,
    CarlaScenarioFixture,
    EgoConfig,
    ScenarioQueue,
    ScenarioResult,
    SpawnTransform,
    TickSnapshot,
)


# ---------------------------------------------------------------------------
# Shared test helpers — imported by unit test modules
# ---------------------------------------------------------------------------


def make_tick_snapshot(
    world: object,
    elapsed: float = 0.0,
    tick_count: int = 1,
    delta_time: float = 0.05,
) -> TickSnapshot:
    """Create a :class:`TickSnapshot` for unit tests."""
    return TickSnapshot(
        world=world,
        elapsed=elapsed,
        tick_count=tick_count,
        delta_time=delta_time,
    )


class AlwaysPassCondition(BaseCondition):
    """Test helper: always returns a passing result."""

    def __init__(self) -> None:
        super().__init__(label="always_pass")

    def check(self, snapshot: TickSnapshot) -> Optional[ScenarioResult]:
        return ScenarioResult(
            passed=True, message="Always passes", elapsed_seconds=snapshot.elapsed
        )


class AlwaysNoneCondition(BaseCondition):
    """Test helper: never triggers."""

    def __init__(self) -> None:
        super().__init__(label="always_none")

    def check(self, snapshot: TickSnapshot) -> Optional[ScenarioResult]:
        return None


class AlwaysFailCondition(BaseCondition):
    """Test helper: always returns a failing result."""

    def __init__(self) -> None:
        super().__init__(label="always_fail")

    def check(self, snapshot: TickSnapshot) -> Optional[ScenarioResult]:
        return ScenarioResult(
            passed=False, message="Always fails", elapsed_seconds=snapshot.elapsed
        )


# ---------------------------------------------------------------------------
# Minimal scenarios used by integration tests
# ---------------------------------------------------------------------------


class _ImmediateScenario(BaseScenario):
    """Scenario that completes immediately (is_done returns True on first call)."""

    def setup(self) -> None:
        pass

    def is_done(self) -> bool:
        return True


# ---------------------------------------------------------------------------
# Queue – populated at import time so all scenarios are registered before
# the session fixture starts the CARLA server.
# ---------------------------------------------------------------------------

_INTEGRATION_EGO = EgoConfig(
    spawn_location=SpawnTransform(
        _carla.Transform(_carla.Location(x=0.0, y=0.0, z=0.0))
    ),
    vehicle_type="vehicle.mini.cooper",
)

_queue = ScenarioQueue(map_name="Town10HD_Opt")

# Register integration scenarios.  Add more CarlaScenarioFixture calls here
# as needed; they will all run in the same CARLA session.
immediate_scenario_result = CarlaScenarioFixture(
    _ImmediateScenario,
    _INTEGRATION_EGO,
    queue=_queue,
).as_fixture()

another_immediate_result = CarlaScenarioFixture(
    _ImmediateScenario,
    _INTEGRATION_EGO,
    queue=_queue,
).as_fixture()


# ---------------------------------------------------------------------------
# Session fixture – auto-skip when CARLA is unavailable (baked into as_fixture)
# ---------------------------------------------------------------------------

carla_queue = _queue.as_fixture()
