"""Session-scoped fixtures for CARLA integration tests.

Architecture
------------
All scenarios are registered into ``_queue`` at module import time (before
any fixture runs).  The single session-scoped ``carla_queue`` fixture starts
the CARLA server once, runs every registered scenario via
:meth:`ScenarioQueue.run_all`, and yields the queue.  Individual test fixtures
then simply call :meth:`ScenarioQueue.result_for` — CARLA is never restarted
between test cases.

Skipping
--------
``carla_queue`` is generated by :meth:`ScenarioQueue.as_fixture`, which
automatically skips when ``CARLA_EXECUTABLE`` is not set or when the
CARLA session cannot be established.

CARLA availability
-------------------
CARLA itself ships x86_64-only wheels, so it is not installable on an
arm64-native interpreter (see the ``dev-nocarla``/``pytest-native`` targets).
The list of CARLA-dependent test modules to exclude from collection lives in
``collect_ignore`` in the testpath-root ``autoware_carla_scenario/test/conftest.py``,
not here: pytest emits ``pytest_report_header`` output before collection
starts, but this subdirectory's conftest is only loaded once collection
descends into ``carla_scenario/``, which is too late for a header hook
defined here to ever fire (confirmed empirically under both serial and
``-n`` xdist runs).

This module still needs its own ``_CARLA_AVAILABLE`` guard below, though:
even with the CARLA-dependent modules ignored at the root, pytest still
descends into this directory to collect the remaining carla-free test
files, so this conftest is always imported regardless of what the root
ignores. Importing ``carla`` unconditionally here would break collection
on arm64-native.
"""

from __future__ import annotations

import importlib.util

_CARLA_AVAILABLE = importlib.util.find_spec("carla") is not None

if _CARLA_AVAILABLE:
    import carla as _carla

    from autoware_carla_scenario import (
        BaseScenario,
        CarlaScenarioFixture,
        EgoConfig,
        ScenarioQueue,
        SpawnTransform,
    )

    # ---------------------------------------------------------------------------
    # Minimal scenarios used by integration tests
    # ---------------------------------------------------------------------------

    class _ImmediateScenario(BaseScenario):
        """Scenario that completes immediately (is_done returns True on first call)."""

        def setup(self) -> None:
            pass

        def is_done(self) -> bool:
            return True

    # ---------------------------------------------------------------------------
    # Queue – populated at import time so all scenarios are registered before
    # the session fixture starts the CARLA server.
    # ---------------------------------------------------------------------------

    _INTEGRATION_EGO = EgoConfig(
        spawn_location=SpawnTransform(
            _carla.Transform(_carla.Location(x=0.0, y=0.0, z=0.0))
        ),
        vehicle_type="vehicle.mini.cooper",
    )

    _queue = ScenarioQueue(map_name="Town10HD_Opt")

    # Register integration scenarios.  Add more CarlaScenarioFixture calls here
    # as needed; they will all run in the same CARLA session.
    immediate_scenario_result = CarlaScenarioFixture(
        _ImmediateScenario,
        _INTEGRATION_EGO,
        queue=_queue,
    ).as_fixture()

    another_immediate_result = CarlaScenarioFixture(
        _ImmediateScenario,
        _INTEGRATION_EGO,
        queue=_queue,
    ).as_fixture()

    # ---------------------------------------------------------------------------
    # Session fixture – auto-skip when CARLA is unavailable (baked into as_fixture)
    # ---------------------------------------------------------------------------

    carla_queue = _queue.as_fixture()

# No `else`/`collect_ignore` branch here: see the "CARLA availability" note
# in the module docstring above -- the ignore list and the
# `pytest_report_header` hook both live in the testpath-root
# ../conftest.py instead, since that is loaded early enough for the header
# hook to actually run.
