repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: 'mkdocs\.yml$'
      - id: check-added-large-files
        exclude: '\.(osm|png|whl)$'
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending

  # - repo: https://github.com/psf/black
  #   rev: 24.10.0
  #   hooks:
  #     - id: black
  #       language_version: python3.10

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        args:
          - --ignore-missing-imports
          - autoware_lanelet2_to_opendrive/src
          - autoware_lanelet2_to_opendrive/test
          - autoware_carla_scenario/src
          - autoware_carla_scenario/test
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest --no-testmon
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
