# # Generated by autoware_carla_scenario/scripts/compile_protos.py -- do not edit.
# #
# # Source: proto/autoware_bridge/v0/autoware_bridge.proto (this repository)
# # Regenerate with: uv run python autoware_carla_scenario/scripts/compile_protos.py

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Mapping as _Mapping, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class Vector3(_message.Message):
    __slots__ = ("x", "y", "z")
    X_FIELD_NUMBER: _ClassVar[int]
    Y_FIELD_NUMBER: _ClassVar[int]
    Z_FIELD_NUMBER: _ClassVar[int]
    x: float
    y: float
    z: float
    def __init__(self, x: _Optional[float] = ..., y: _Optional[float] = ..., z: _Optional[float] = ...) -> None: ...

class Quaternion(_message.Message):
    __slots__ = ("w", "x", "y", "z")
    W_FIELD_NUMBER: _ClassVar[int]
    X_FIELD_NUMBER: _ClassVar[int]
    Y_FIELD_NUMBER: _ClassVar[int]
    Z_FIELD_NUMBER: _ClassVar[int]
    w: float
    x: float
    y: float
    z: float
    def __init__(self, w: _Optional[float] = ..., x: _Optional[float] = ..., y: _Optional[float] = ..., z: _Optional[float] = ...) -> None: ...

class Pose(_message.Message):
    __slots__ = ("position", "rotation")
    POSITION_FIELD_NUMBER: _ClassVar[int]
    ROTATION_FIELD_NUMBER: _ClassVar[int]
    position: Vector3
    rotation: Quaternion
    def __init__(self, position: _Optional[_Union[Vector3, _Mapping]] = ..., rotation: _Optional[_Union[Quaternion, _Mapping]] = ...) -> None: ...

class GetMissionRequest(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class GetMissionResponse(_message.Message):
    __slots__ = ("available", "initial_pose", "goal")
    AVAILABLE_FIELD_NUMBER: _ClassVar[int]
    INITIAL_POSE_FIELD_NUMBER: _ClassVar[int]
    GOAL_FIELD_NUMBER: _ClassVar[int]
    available: bool
    initial_pose: Pose
    goal: Pose
    def __init__(self, available: bool = ..., initial_pose: _Optional[_Union[Pose, _Mapping]] = ..., goal: _Optional[_Union[Pose, _Mapping]] = ...) -> None: ...

class ReportReadinessRequest(_message.Message):
    __slots__ = ("ready",)
    READY_FIELD_NUMBER: _ClassVar[int]
    ready: bool
    def __init__(self, ready: bool = ...) -> None: ...

class ReportReadinessResponse(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...
