"""Render transpiled scenarios as a standalone *scenario package*.

Instead of a single self-contained module (see :mod:`.codegen`), this produces
the installable package layout introduced in ``autoware_carla_scenario`` — a
``pyproject.toml`` with an ``autoware_carla_scenario.scenarios`` entry point,
``src/<pkg>/{__init__,configs,<scenario>}.py`` and per-variant Hydra configs:

    <package>/
        pyproject.toml
        README.md
        src/<package>/
            __init__.py                              # register() hooks
            <scenario>.py                            # transpiled BaseScenario(s)
            configs.py                               # config dataclass
            conf/scenario/<variant>/default.yaml     # concrete values

Each ``one_of`` variant becomes a separately registered scenario, so the package
plugs straight into the framework's ``uv run scenario`` / multirun flow.
"""

from __future__ import annotations

from dataclasses import replace

from .codegen import _INDENT, _Emitter, _indent, _setup_body
from .plan import ScenarioPlan, Spec, SpecKind

#: Default fail-safe timeout (seconds) when the DSL declares none.
_DEFAULT_TIMEOUT_SECONDS = 60.0


def _variant_names(base_scenario: str, base_class: str, index: int, count: int):
    if count == 1:
        return base_scenario, base_class
    return f"{base_scenario}_v{index}", f"{base_class}V{index}"


def _default_timeout(plans: list[ScenarioPlan]) -> float:
    for plan in plans:
        for spec in plan.specs:
            if spec.kind is SpecKind.TIMEOUT:
                return float(spec.params["seconds"])
    return _DEFAULT_TIMEOUT_SECONDS


def _ensure_timeout(plan: ScenarioPlan, seconds: float) -> None:
    """Guarantee a config-driven timeout fail-condition exists on *plan*."""
    if not any(s.kind is SpecKind.TIMEOUT for s in plan.specs):
        plan.specs.append(
            Spec(
                kind=SpecKind.TIMEOUT,
                actor=plan.ego.name,
                label="scenario_timeout",
                params={"seconds": seconds},
            )
        )


# ---------------------------------------------------------------------------
# Individual files
# ---------------------------------------------------------------------------


def _render_scenario_class(
    plan: ScenarioPlan, class_name: str, config_class: str, emitter: _Emitter
) -> list[str]:
    variant_note = f" (variant {plan.variant_index})" if plan.variant_count > 1 else ""
    setup_body = _setup_body(plan, emitter)
    return [
        f"class {class_name}(BaseScenario):",
        f'{_INDENT}"""Transpiled scenario {plan.name!r}{variant_note}."""',
        "",
        f"{_INDENT}def __init__(",
        f"{_INDENT * 2}self,",
        f"{_INDENT * 2}ego_config: EgoConfig,",
        f"{_INDENT * 2}spawn_pose: Lanelet2Pose,",
        f"{_INDENT * 2}config: {config_class} | None = None,",
        f"{_INDENT * 2}ground_projection: GroundProjectionConfig | None = None,",
        f"{_INDENT}) -> None:",
        f"{_INDENT * 2}super().__init__(",
        f"{_INDENT * 3}ego_config, spawn_pose=spawn_pose, "
        "ground_projection=ground_projection,",
        f"{_INDENT * 2})",
        f"{_INDENT * 2}self._config = config or {config_class}()",
        "",
        f"{_INDENT}def setup(self) -> None:",
        *_indent(setup_body, 2),
        "",
        f"{_INDENT}def is_done(self) -> bool:",
        f"{_INDENT * 2}return False",
    ]


def _render_scenario_module(
    plans: list[ScenarioPlan],
    *,
    source_name: str,
    class_names: list[str],
    config_class: str,
) -> str:
    emitter = _Emitter()
    class_blocks = [
        _render_scenario_class(plan, class_names[i], config_class, emitter)
        for i, plan in enumerate(plans)
    ]

    names = sorted(
        emitter.imports
        | {"BaseScenario", "EgoConfig", "GroundProjectionConfig", "Lanelet2Pose"}
    )
    lines = [
        '"""Scenario(s) transpiled from an OpenSCENARIO DSL source.',
        "",
        f"Source: {source_name}",
        "",
        "Generated by autoware_carla_scenario.openscenario_dsl_frontend.",
        "Edit freely — this file is plain, readable scenario code.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]
    if emitter.needs_carla:
        lines += ["import carla", ""]
    lines += ["from autoware_carla_scenario import ("]
    lines += [f"{_INDENT}{name}," for name in names]
    lines += [")", "", f"from .configs import {config_class}", "", ""]
    for block in class_blocks:
        lines += block
        lines += ["", ""]
    return "\n".join(lines).rstrip("\n") + "\n"


def _render_configs(config_class: str, scenario_name: str, timeout: float) -> str:
    return (
        f'"""Config dataclass for the transpiled {scenario_name!r} scenario."""\n\n'
        "from __future__ import annotations\n\n"
        "from dataclasses import dataclass\n\n\n"
        "@dataclass\n"
        f"class {config_class}:\n"
        f'    """Overridable parameters (via Hydra / the scenario YAML)."""\n\n'
        "    #: Must match the registered scenario name and the YAML "
        "``scenario.name``.\n"
        f'    name: str = "{scenario_name}"\n\n'
        "    #: Fail-safe timeout in seconds.\n"
        f"    timeout_seconds: float = {timeout!r}\n"
    )


def _render_init(
    package_name: str,
    scenario_module: str,
    config_class: str,
    description: str,
    variants: list[tuple[str, str]],
) -> str:
    class_imports = "".join(f"{_INDENT * 2}{cls},\n" for _, cls in variants)
    registrations = "".join(
        f'{_INDENT}register_scenario("{name}", {cls}, {config_class})\n'
        for name, cls in variants
    )
    return (
        f'"""{description}\n\n'
        "Installing this package makes its transpiled scenario(s) available to\n"
        "``uv run scenario`` via the ``autoware_carla_scenario.scenarios`` entry\n"
        'point — no edits to ``autoware_carla_scenario`` required."""\n\n'
        "from __future__ import annotations\n\n"
        "from pathlib import Path\n\n"
        "from autoware_carla_scenario import register_conf_dir, register_scenario\n\n"
        f"from .configs import {config_class}\n\n"
        f'__all__ = ["{config_class}", "register"]\n\n'
        "#: Directory holding this package's Hydra config groups.\n"
        'CONF_DIR = Path(__file__).resolve().parent / "conf"\n\n\n'
        "def register() -> None:\n"
        '    """Register this package\'s scenarios and config directory."""\n'
        f"    from .{scenario_module} import (\n"
        f"{class_imports}"
        "    )\n\n"
        f"{registrations}"
        "    register_conf_dir(CONF_DIR)\n"
    )


def _render_pyproject(
    distribution_name: str, package_name: str, description: str
) -> str:
    return (
        "[project]\n"
        f'name = "{distribution_name}"\n'
        'version = "0.1.0"\n'
        f'description = "{description}"\n'
        'requires-python = ">=3.10,<3.11"\n'
        "dependencies = [\n"
        '    "autoware-carla-scenario",\n'
        "]\n\n"
        '[project.entry-points."autoware_carla_scenario.scenarios"]\n'
        f'{package_name} = "{package_name}:register"\n\n'
        "[build-system]\n"
        'requires = ["uv_build>=0.9.7,<0.10.0"]\n'
        'build-backend = "uv_build"\n\n'
        "[tool.uv-build]\n"
        f'packages = ["src/{package_name}"]\n'
    )


def _collect_notes(plans: list[ScenarioPlan]) -> list[str]:
    """Aggregate transpiler notes across variants, preserving first-seen order."""
    seen: set[str] = set()
    notes: list[str] = []
    for plan in plans:
        for note in plan.notes:
            if note not in seen:
                seen.add(note)
                notes.append(note)
    return notes


def _render_readme(
    distribution_name: str,
    scenario_names: list[str],
    source_name: str,
    plans: list[ScenarioPlan],
) -> str:
    runs = "\n".join(
        f"uv run scenario scenario={name}/default map=nishishinjuku"
        for name in scenario_names
    )
    body = (
        f"# {distribution_name}\n\n"
        f"Scenario package transpiled from `{source_name}` by "
        "`autoware_carla_scenario.openscenario_dsl_frontend`.\n\n"
        "## Install & run\n\n"
        "```bash\n"
        "uv pip install -e .\n"
        f"{runs}\n"
        "```\n"
    )
    map_hint = next((p.map_hint for p in plans if p.map_hint), None)
    if map_hint is not None:
        body += (
            f"\n## Map\n\nThe source targeted map `{map_hint}`. The map is "
            "selected at run time via `map=...`, so this is advisory only.\n"
        )
    if any(p.sweep_constraints for p in plans):
        body += (
            "\n## Spawn selection (lanelet-constraint sweep)\n\n"
            "The source constrained the spawn road (e.g. "
            "`path_min_driving_lanes`). The config declares a `sweep` section "
            "that resolves `ego.spawn_lanelet_id` against the chosen map. Run "
            "it through the lanelet-constraint sweeper:\n\n"
            "```bash\n"
            f"uv run scenario --multirun scenario={scenario_names[0]}/default "
            "map=nishishinjuku hydra/sweeper=lanelet_constraint\n"
            "```\n"
        )
    notes = _collect_notes(plans)
    if notes:
        body += "\n## Transpiler notes\n\n"
        body += "Constructs approximated or deferred during transpilation:\n\n"
        body += "".join(f"- {note}\n" for note in notes)
    return body


def _yaml_scalar(value: object) -> str:
    """Render a scalar for the generated YAML."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    return str(value)


def _yaml_lines(obj: object, indent: int = 0) -> list[str]:
    """Render a nested dict/list/scalar structure as block-style YAML lines."""
    pad = "  " * indent
    lines: list[str] = []
    if isinstance(obj, dict):
        for key, value in obj.items():
            if isinstance(value, (dict, list)):
                lines.append(f"{pad}{key}:")
                lines.extend(_yaml_lines(value, indent + 1))
            else:
                lines.append(f"{pad}{key}: {_yaml_scalar(value)}")
    elif isinstance(obj, list):
        for item in obj:
            if isinstance(item, (dict, list)):
                inner = _yaml_lines(item, indent + 1)
                # Turn the first inner line into a "- " list entry.
                lines.append(f"{pad}- {inner[0].lstrip()}")
                lines.extend(inner[1:])
            else:
                lines.append(f"{pad}- {_yaml_scalar(item)}")
    else:
        lines.append(f"{pad}{_yaml_scalar(obj)}")
    return lines


def _render_default_yaml(plan: ScenarioPlan, scenario_name: str, timeout: float) -> str:
    ego = plan.ego
    lanelet = ego.spawn_lanelet_id if ego.spawn_lanelet_id is not None else 0
    note = "" if ego.spawn_lanelet_id is not None else "  # overridden by sweep below"
    if ego.spawn_lanelet_id is None and not plan.sweep_constraints:
        note = "  # TODO: set spawn lanelet"
    text = (
        "# @package _global_\n"
        f"# Concrete values for the transpiled {scenario_name!r} scenario.\n"
        "scenario:\n"
        f"  name: {scenario_name}\n"
        f"  timeout_seconds: {timeout}\n\n"
        "ego:\n"
        f"  initial_speed_kmh: {ego.initial_speed_kmh}\n"
        f"  spawn_lanelet_id: {lanelet}{note}\n"
        f"  spawn_s: {ego.spawn_s}\n"
    )
    if plan.sweep_constraints:
        # Resolve the spawn lanelet against the map via the lanelet-constraint
        # sweeper (run with `--multirun hydra/sweeper=lanelet_constraint`).
        block = _yaml_lines({"sweep": {"constraints": plan.sweep_constraints}})
        text += "\n" + "\n".join(block) + "\n"
    return text


# ---------------------------------------------------------------------------
# Package assembly
# ---------------------------------------------------------------------------


def generate_package_files(
    plans: list[ScenarioPlan],
    *,
    source_name: str,
    package_name: str | None = None,
    description: str | None = None,
) -> dict[str, str]:
    """Render a full scenario package as ``{relative_path: file_content}``.

    Args:
        plans: The transpiled scenario variants (one per ``one_of`` branch).
        source_name: The originating ``.osc`` path (recorded in docstrings).
        package_name: Desired package name; defaults to ``<scenario>_package``.
        description: Optional package description.

    Returns:
        A mapping of package-relative file paths to their contents.
    """
    if not plans:
        raise ValueError("generate_package_files requires at least one plan")

    # Imported lazily: pulls in jinja2 via the scaffold module, which the rest
    # of the frontend does not need.
    from ..scaffold.generator import resolve_names

    base_dsl_name = plans[0].name.split(".")[-1]
    raw_name = package_name or f"{base_dsl_name}_package"
    names = resolve_names(raw_name, description=description)
    pkg = names["package_name"]
    base_scenario = names["scenario_name"]
    base_class = names["scenario_class"]
    config_class = names["config_class"]
    description = names["description"]

    # Work on copies so injected timeouts don't leak into the caller's plans.
    plans = [replace(p, specs=list(p.specs)) for p in plans]
    timeout = _default_timeout(plans)
    for plan in plans:
        _ensure_timeout(plan, timeout)

    count = len(plans)
    variant_scn: list[str] = []
    variant_cls: list[str] = []
    for i in range(count):
        scn, cls = _variant_names(base_scenario, base_class, i, count)
        variant_scn.append(scn)
        variant_cls.append(cls)

    scenario_module = _render_scenario_module(
        plans,
        source_name=source_name,
        class_names=variant_cls,
        config_class=config_class,
    )

    files: dict[str, str] = {
        "pyproject.toml": _render_pyproject(
            names["distribution_name"], pkg, description
        ),
        "README.md": _render_readme(
            names["distribution_name"], variant_scn, source_name, plans
        ),
        f"src/{pkg}/__init__.py": _render_init(
            pkg,
            base_scenario,
            config_class,
            description,
            list(zip(variant_scn, variant_cls)),
        ),
        f"src/{pkg}/{base_scenario}.py": scenario_module,
        f"src/{pkg}/configs.py": _render_configs(config_class, base_scenario, timeout),
    }
    for plan, scn in zip(plans, variant_scn):
        files[f"src/{pkg}/conf/scenario/{scn}/default.yaml"] = _render_default_yaml(
            plan, scn, timeout
        )
    return files
