# Generated by autoware_carla_scenario/scripts/compile_protos.py -- do not edit.
#
# Sources: NVlabs/alpasim@6870924 and
#          hakuturu583/carla_driver_interface@af1dcd3 (both Apache-2.0)
# Regenerate with: uv run python autoware_carla_scenario/scripts/compile_protos.py

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alpasim_grpc/v0/common.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61lpasim_grpc/v0/common.proto\x12\x06\x63ommon\"\x07\n\x05\x45mpty\"2\n\x04Quat\x12\t\n\x01w\x18\x01 \x01(\x02\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\"\'\n\x04Vec3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"=\n\x04Pose\x12\x19\n\x03vec\x18\x01 \x01(\x0b\x32\x0c.common.Vec3\x12\x1a\n\x04quat\x18\x02 \x01(\x0b\x32\x0c.common.Quat\"\xb4\x01\n\x0c\x44ynamicState\x12&\n\x10\x61ngular_velocity\x18\x01 \x01(\x0b\x32\x0c.common.Vec3\x12%\n\x0flinear_velocity\x18\x02 \x01(\x0b\x32\x0c.common.Vec3\x12)\n\x13linear_acceleration\x18\x03 \x01(\x0b\x32\x0c.common.Vec3\x12*\n\x14\x61ngular_acceleration\x18\x04 \x01(\x0b\x32\x0c.common.Vec3\"6\n\x04\x41\x41\x42\x42\x12\x0e\n\x06size_x\x18\x01 \x01(\x02\x12\x0e\n\x06size_y\x18\x02 \x01(\x02\x12\x0e\n\x06size_z\x18\x03 \x01(\x02\">\n\nPoseAtTime\x12\x1a\n\x04pose\x18\x01 \x01(\x0b\x32\x0c.common.Pose\x12\x14\n\x0ctimestamp_us\x18\x02 \x01(\x06\"d\n\x0bStateAtTime\x12\x14\n\x0ctimestamp_us\x18\x01 \x01(\x06\x12\x1a\n\x04pose\x18\x02 \x01(\x0b\x32\x0c.common.Pose\x12#\n\x05state\x18\x03 \x01(\x0b\x32\x14.common.DynamicState\"/\n\nTrajectory\x12!\n\x05poses\x18\x01 \x03(\x0b\x32\x12.common.PoseAtTime\"\xa4\x01\n\tVersionId\x12\x12\n\nversion_id\x18\x01 \x01(\t\x12\x10\n\x08git_hash\x18\x02 \x01(\t\x12\x36\n\x10grpc_api_version\x18\x03 \x01(\x0b\x32\x1c.common.VersionId.APIVersion\x1a\x39\n\nAPIVersion\x12\r\n\x05major\x18\x01 \x01(\r\x12\r\n\x05minor\x18\x02 \x01(\r\x12\r\n\x05patch\x18\x03 \x01(\r\"\x16\n\x14SessionRequestStatus\"*\n\x15\x41vailableScenesReturn\x12\x11\n\tscene_ids\x18\x01 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alpasim_grpc.v0.common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=40
  _globals['_EMPTY']._serialized_end=47
  _globals['_QUAT']._serialized_start=49
  _globals['_QUAT']._serialized_end=99
  _globals['_VEC3']._serialized_start=101
  _globals['_VEC3']._serialized_end=140
  _globals['_POSE']._serialized_start=142
  _globals['_POSE']._serialized_end=203
  _globals['_DYNAMICSTATE']._serialized_start=206
  _globals['_DYNAMICSTATE']._serialized_end=386
  _globals['_AABB']._serialized_start=388
  _globals['_AABB']._serialized_end=442
  _globals['_POSEATTIME']._serialized_start=444
  _globals['_POSEATTIME']._serialized_end=506
  _globals['_STATEATTIME']._serialized_start=508
  _globals['_STATEATTIME']._serialized_end=608
  _globals['_TRAJECTORY']._serialized_start=610
  _globals['_TRAJECTORY']._serialized_end=657
  _globals['_VERSIONID']._serialized_start=660
  _globals['_VERSIONID']._serialized_end=824
  _globals['_VERSIONID_APIVERSION']._serialized_start=767
  _globals['_VERSIONID_APIVERSION']._serialized_end=824
  _globals['_SESSIONREQUESTSTATUS']._serialized_start=826
  _globals['_SESSIONREQUESTSTATUS']._serialized_end=848
  _globals['_AVAILABLESCENESRETURN']._serialized_start=850
  _globals['_AVAILABLESCENESRETURN']._serialized_end=892
# @@protoc_insertion_point(module_scope)
