# # Generated by autoware_carla_scenario/scripts/compile_protos.py -- do not edit.
# #
# # Source: NVlabs/alpasim@68709245a5dc0f2eda4f8cb2c3aa8cbdfa913043 (Apache-2.0)
# # Regenerate with: uv run python autoware_carla_scenario/scripts/compile_protos.py

from . import common_pb2 as _common_pb2
from . import sensorsim_pb2 as _sensorsim_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Iterable as _Iterable, Mapping as _Mapping, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class Route(_message.Message):
    __slots__ = ("timestamp_us", "waypoints")
    TIMESTAMP_US_FIELD_NUMBER: _ClassVar[int]
    WAYPOINTS_FIELD_NUMBER: _ClassVar[int]
    timestamp_us: int
    waypoints: _containers.RepeatedCompositeFieldContainer[_common_pb2.Vec3]
    def __init__(self, timestamp_us: _Optional[int] = ..., waypoints: _Optional[_Iterable[_Union[_common_pb2.Vec3, _Mapping]]] = ...) -> None: ...

class GroundTruth(_message.Message):
    __slots__ = ("timestamp_us", "trajectory")
    TIMESTAMP_US_FIELD_NUMBER: _ClassVar[int]
    TRAJECTORY_FIELD_NUMBER: _ClassVar[int]
    timestamp_us: int
    trajectory: _common_pb2.Trajectory
    def __init__(self, timestamp_us: _Optional[int] = ..., trajectory: _Optional[_Union[_common_pb2.Trajectory, _Mapping]] = ...) -> None: ...

class DriveSessionRequest(_message.Message):
    __slots__ = ("session_uuid", "random_seed", "debug_info", "rollout_spec")
    class RolloutSpec(_message.Message):
        __slots__ = ("vehicle",)
        class VehicleDefinition(_message.Message):
            __slots__ = ("available_cameras",)
            AVAILABLE_CAMERAS_FIELD_NUMBER: _ClassVar[int]
            available_cameras: _containers.RepeatedCompositeFieldContainer[_sensorsim_pb2.AvailableCamerasReturn.AvailableCamera]
            def __init__(self, available_cameras: _Optional[_Iterable[_Union[_sensorsim_pb2.AvailableCamerasReturn.AvailableCamera, _Mapping]]] = ...) -> None: ...
        VEHICLE_FIELD_NUMBER: _ClassVar[int]
        vehicle: DriveSessionRequest.RolloutSpec.VehicleDefinition
        def __init__(self, vehicle: _Optional[_Union[DriveSessionRequest.RolloutSpec.VehicleDefinition, _Mapping]] = ...) -> None: ...
    class DebugInfo(_message.Message):
        __slots__ = ("scene_id",)
        SCENE_ID_FIELD_NUMBER: _ClassVar[int]
        scene_id: str
        def __init__(self, scene_id: _Optional[str] = ...) -> None: ...
    SESSION_UUID_FIELD_NUMBER: _ClassVar[int]
    RANDOM_SEED_FIELD_NUMBER: _ClassVar[int]
    DEBUG_INFO_FIELD_NUMBER: _ClassVar[int]
    ROLLOUT_SPEC_FIELD_NUMBER: _ClassVar[int]
    session_uuid: str
    random_seed: int
    debug_info: DriveSessionRequest.DebugInfo
    rollout_spec: DriveSessionRequest.RolloutSpec
    def __init__(self, session_uuid: _Optional[str] = ..., random_seed: _Optional[int] = ..., debug_info: _Optional[_Union[DriveSessionRequest.DebugInfo, _Mapping]] = ..., rollout_spec: _Optional[_Union[DriveSessionRequest.RolloutSpec, _Mapping]] = ...) -> None: ...

class DriveSessionCloseRequest(_message.Message):
    __slots__ = ("session_uuid",)
    SESSION_UUID_FIELD_NUMBER: _ClassVar[int]
    session_uuid: str
    def __init__(self, session_uuid: _Optional[str] = ...) -> None: ...

class RolloutCameraImage(_message.Message):
    __slots__ = ("session_uuid", "camera_image")
    class CameraImage(_message.Message):
        __slots__ = ("frame_start_us", "frame_end_us", "image_bytes", "logical_id")
        FRAME_START_US_FIELD_NUMBER: _ClassVar[int]
        FRAME_END_US_FIELD_NUMBER: _ClassVar[int]
        IMAGE_BYTES_FIELD_NUMBER: _ClassVar[int]
        LOGICAL_ID_FIELD_NUMBER: _ClassVar[int]
        frame_start_us: int
        frame_end_us: int
        image_bytes: bytes
        logical_id: str
        def __init__(self, frame_start_us: _Optional[int] = ..., frame_end_us: _Optional[int] = ..., image_bytes: _Optional[bytes] = ..., logical_id: _Optional[str] = ...) -> None: ...
    SESSION_UUID_FIELD_NUMBER: _ClassVar[int]
    CAMERA_IMAGE_FIELD_NUMBER: _ClassVar[int]
    session_uuid: str
    camera_image: RolloutCameraImage.CameraImage
    def __init__(self, session_uuid: _Optional[str] = ..., camera_image: _Optional[_Union[RolloutCameraImage.CameraImage, _Mapping]] = ...) -> None: ...

class RolloutEgoTrajectory(_message.Message):
    __slots__ = ("session_uuid", "trajectory", "dynamic_states")
    SESSION_UUID_FIELD_NUMBER: _ClassVar[int]
    TRAJECTORY_FIELD_NUMBER: _ClassVar[int]
    DYNAMIC_STATES_FIELD_NUMBER: _ClassVar[int]
    session_uuid: str
    trajectory: _common_pb2.Trajectory
    dynamic_states: _containers.RepeatedCompositeFieldContainer[_common_pb2.DynamicState]
    def __init__(self, session_uuid: _Optional[str] = ..., trajectory: _Optional[_Union[_common_pb2.Trajectory, _Mapping]] = ..., dynamic_states: _Optional[_Iterable[_Union[_common_pb2.DynamicState, _Mapping]]] = ...) -> None: ...

class RouteRequest(_message.Message):
    __slots__ = ("session_uuid", "route")
    SESSION_UUID_FIELD_NUMBER: _ClassVar[int]
    ROUTE_FIELD_NUMBER: _ClassVar[int]
    session_uuid: str
    route: Route
    def __init__(self, session_uuid: _Optional[str] = ..., route: _Optional[_Union[Route, _Mapping]] = ...) -> None: ...

class GroundTruthRequest(_message.Message):
    __slots__ = ("session_uuid", "ground_truth")
    SESSION_UUID_FIELD_NUMBER: _ClassVar[int]
    GROUND_TRUTH_FIELD_NUMBER: _ClassVar[int]
    session_uuid: str
    ground_truth: GroundTruth
    def __init__(self, session_uuid: _Optional[str] = ..., ground_truth: _Optional[_Union[GroundTruth, _Mapping]] = ...) -> None: ...

class DriveRequest(_message.Message):
    __slots__ = ("session_uuid", "time_now_us", "time_query_us", "renderer_data")
    class RolloutDriveRequest(_message.Message):
        __slots__ = ("time_now_us", "time_query_us")
        TIME_NOW_US_FIELD_NUMBER: _ClassVar[int]
        TIME_QUERY_US_FIELD_NUMBER: _ClassVar[int]
        time_now_us: int
        time_query_us: int
        def __init__(self, time_now_us: _Optional[int] = ..., time_query_us: _Optional[int] = ...) -> None: ...
    SESSION_UUID_FIELD_NUMBER: _ClassVar[int]
    TIME_NOW_US_FIELD_NUMBER: _ClassVar[int]
    TIME_QUERY_US_FIELD_NUMBER: _ClassVar[int]
    RENDERER_DATA_FIELD_NUMBER: _ClassVar[int]
    session_uuid: str
    time_now_us: int
    time_query_us: int
    renderer_data: bytes
    def __init__(self, session_uuid: _Optional[str] = ..., time_now_us: _Optional[int] = ..., time_query_us: _Optional[int] = ..., renderer_data: _Optional[bytes] = ...) -> None: ...

class DriveResponse(_message.Message):
    __slots__ = ("trajectory", "debug_info", "terminate_session")
    class DebugInfo(_message.Message):
        __slots__ = ("unstructured_debug_info", "sampled_trajectories")
        UNSTRUCTURED_DEBUG_INFO_FIELD_NUMBER: _ClassVar[int]
        SAMPLED_TRAJECTORIES_FIELD_NUMBER: _ClassVar[int]
        unstructured_debug_info: bytes
        sampled_trajectories: _containers.RepeatedCompositeFieldContainer[_common_pb2.Trajectory]
        def __init__(self, unstructured_debug_info: _Optional[bytes] = ..., sampled_trajectories: _Optional[_Iterable[_Union[_common_pb2.Trajectory, _Mapping]]] = ...) -> None: ...
    TRAJECTORY_FIELD_NUMBER: _ClassVar[int]
    DEBUG_INFO_FIELD_NUMBER: _ClassVar[int]
    TERMINATE_SESSION_FIELD_NUMBER: _ClassVar[int]
    trajectory: _common_pb2.Trajectory
    debug_info: DriveResponse.DebugInfo
    terminate_session: bool
    def __init__(self, trajectory: _Optional[_Union[_common_pb2.Trajectory, _Mapping]] = ..., debug_info: _Optional[_Union[DriveResponse.DebugInfo, _Mapping]] = ..., terminate_session: bool = ...) -> None: ...
