# Generated by autoware_carla_scenario/scripts/compile_protos.py -- do not edit.
#
# Sources: NVlabs/alpasim@6870924 and
#          hakuturu583/carla_driver_interface@af1dcd3 (both Apache-2.0)
# Regenerate with: uv run python autoware_carla_scenario/scripts/compile_protos.py

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import common_pb2 as alpasim__grpc_dot_v0_dot_common__pb2
from . import egodriver_pb2 as alpasim__grpc_dot_v0_dot_egodriver__pb2


class EgodriverServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.start_session = channel.unary_unary(
                '/egodriver.EgodriverService/start_session',
                request_serializer=alpasim__grpc_dot_v0_dot_egodriver__pb2.DriveSessionRequest.SerializeToString,
                response_deserializer=alpasim__grpc_dot_v0_dot_common__pb2.SessionRequestStatus.FromString,
                )
        self.close_session = channel.unary_unary(
                '/egodriver.EgodriverService/close_session',
                request_serializer=alpasim__grpc_dot_v0_dot_egodriver__pb2.DriveSessionCloseRequest.SerializeToString,
                response_deserializer=alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
                )
        self.submit_image_observation = channel.unary_unary(
                '/egodriver.EgodriverService/submit_image_observation',
                request_serializer=alpasim__grpc_dot_v0_dot_egodriver__pb2.RolloutCameraImage.SerializeToString,
                response_deserializer=alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
                )
        self.submit_egomotion_observation = channel.unary_unary(
                '/egodriver.EgodriverService/submit_egomotion_observation',
                request_serializer=alpasim__grpc_dot_v0_dot_egodriver__pb2.RolloutEgoTrajectory.SerializeToString,
                response_deserializer=alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
                )
        self.submit_route = channel.unary_unary(
                '/egodriver.EgodriverService/submit_route',
                request_serializer=alpasim__grpc_dot_v0_dot_egodriver__pb2.RouteRequest.SerializeToString,
                response_deserializer=alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
                )
        self.submit_recording_ground_truth = channel.unary_unary(
                '/egodriver.EgodriverService/submit_recording_ground_truth',
                request_serializer=alpasim__grpc_dot_v0_dot_egodriver__pb2.GroundTruthRequest.SerializeToString,
                response_deserializer=alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
                )
        self.drive = channel.unary_unary(
                '/egodriver.EgodriverService/drive',
                request_serializer=alpasim__grpc_dot_v0_dot_egodriver__pb2.DriveRequest.SerializeToString,
                response_deserializer=alpasim__grpc_dot_v0_dot_egodriver__pb2.DriveResponse.FromString,
                )
        self.get_version = channel.unary_unary(
                '/egodriver.EgodriverService/get_version',
                request_serializer=alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=alpasim__grpc_dot_v0_dot_common__pb2.VersionId.FromString,
                )


class EgodriverServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def start_session(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def close_session(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submit_image_observation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submit_egomotion_observation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submit_route(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submit_recording_ground_truth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def drive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_version(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EgodriverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'start_session': grpc.unary_unary_rpc_method_handler(
                    servicer.start_session,
                    request_deserializer=alpasim__grpc_dot_v0_dot_egodriver__pb2.DriveSessionRequest.FromString,
                    response_serializer=alpasim__grpc_dot_v0_dot_common__pb2.SessionRequestStatus.SerializeToString,
            ),
            'close_session': grpc.unary_unary_rpc_method_handler(
                    servicer.close_session,
                    request_deserializer=alpasim__grpc_dot_v0_dot_egodriver__pb2.DriveSessionCloseRequest.FromString,
                    response_serializer=alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
            ),
            'submit_image_observation': grpc.unary_unary_rpc_method_handler(
                    servicer.submit_image_observation,
                    request_deserializer=alpasim__grpc_dot_v0_dot_egodriver__pb2.RolloutCameraImage.FromString,
                    response_serializer=alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
            ),
            'submit_egomotion_observation': grpc.unary_unary_rpc_method_handler(
                    servicer.submit_egomotion_observation,
                    request_deserializer=alpasim__grpc_dot_v0_dot_egodriver__pb2.RolloutEgoTrajectory.FromString,
                    response_serializer=alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
            ),
            'submit_route': grpc.unary_unary_rpc_method_handler(
                    servicer.submit_route,
                    request_deserializer=alpasim__grpc_dot_v0_dot_egodriver__pb2.RouteRequest.FromString,
                    response_serializer=alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
            ),
            'submit_recording_ground_truth': grpc.unary_unary_rpc_method_handler(
                    servicer.submit_recording_ground_truth,
                    request_deserializer=alpasim__grpc_dot_v0_dot_egodriver__pb2.GroundTruthRequest.FromString,
                    response_serializer=alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
            ),
            'drive': grpc.unary_unary_rpc_method_handler(
                    servicer.drive,
                    request_deserializer=alpasim__grpc_dot_v0_dot_egodriver__pb2.DriveRequest.FromString,
                    response_serializer=alpasim__grpc_dot_v0_dot_egodriver__pb2.DriveResponse.SerializeToString,
            ),
            'get_version': grpc.unary_unary_rpc_method_handler(
                    servicer.get_version,
                    request_deserializer=alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
                    response_serializer=alpasim__grpc_dot_v0_dot_common__pb2.VersionId.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'egodriver.EgodriverService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EgodriverService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def start_session(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/egodriver.EgodriverService/start_session',
            alpasim__grpc_dot_v0_dot_egodriver__pb2.DriveSessionRequest.SerializeToString,
            alpasim__grpc_dot_v0_dot_common__pb2.SessionRequestStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def close_session(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/egodriver.EgodriverService/close_session',
            alpasim__grpc_dot_v0_dot_egodriver__pb2.DriveSessionCloseRequest.SerializeToString,
            alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def submit_image_observation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/egodriver.EgodriverService/submit_image_observation',
            alpasim__grpc_dot_v0_dot_egodriver__pb2.RolloutCameraImage.SerializeToString,
            alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def submit_egomotion_observation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/egodriver.EgodriverService/submit_egomotion_observation',
            alpasim__grpc_dot_v0_dot_egodriver__pb2.RolloutEgoTrajectory.SerializeToString,
            alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def submit_route(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/egodriver.EgodriverService/submit_route',
            alpasim__grpc_dot_v0_dot_egodriver__pb2.RouteRequest.SerializeToString,
            alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def submit_recording_ground_truth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/egodriver.EgodriverService/submit_recording_ground_truth',
            alpasim__grpc_dot_v0_dot_egodriver__pb2.GroundTruthRequest.SerializeToString,
            alpasim__grpc_dot_v0_dot_common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def drive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/egodriver.EgodriverService/drive',
            alpasim__grpc_dot_v0_dot_egodriver__pb2.DriveRequest.SerializeToString,
            alpasim__grpc_dot_v0_dot_egodriver__pb2.DriveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/egodriver.EgodriverService/get_version',
            alpasim__grpc_dot_v0_dot_common__pb2.Empty.SerializeToString,
            alpasim__grpc_dot_v0_dot_common__pb2.VersionId.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
