"""autoware_carla_scenario – CARLA scenario testing framework.

Public API re-exported for convenience::

    from autoware_carla_scenario import (
        EGO_ROLE_NAME,
        ScenarioRunner,
        CarlaScenarioFixture,
        CarlaServerManager,
        AndCondition,
        BaseCondition,
        BaseScenario,
        CarlaWorldPose,
        CollisionCondition,
        ComparisonRule,
        ElapsedTimeCondition,
        EntityInAreaCondition,
        EntityLanePositionCondition,
        OrCondition,
        SpeedCondition,
        SpeedCoordinateSystem,
        SpeedDirection,
        StandstillCondition,
        StickyCondition,
        EgoConfig,
        EgoVehicle,
        Lanelet2Pose,
        MapManager,
        OpenDrivePose,
        ScenarioQueue,
        ScenarioResult,
        TimeoutCondition,
        to_carla_location,
        to_carla_world,
        to_lanelet2,
        to_opendrive,
        find_nearest_traffic_light,
        frame_of,
        lanelet2_traffic_light_id_to_opendrive_controller_id,
        find_actor_by_role_name,
        set_all_traffic_lights_state,
        set_group_traffic_light_state,
        # Entity
        SpawnLocation,
        SpawnPointIndex,
        SpawnTransform,
        VehicleEntity,
        VehicleEntityConfig,
        # Kinematics
        CoordinateFrame,
        FrameMismatchError,
        Vector3,
        AbsoluteVelocity,
        RelativeVelocity,
        FrenetVelocity,
        AbsoluteAcceleration,
        RelativeAcceleration,
        FrenetAcceleration,
    )
"""

from .actions import BaseAction, TickTiming, TurnAction, TurnDirection
from .scenario_runner import ScenarioRunner
from .conditions import (
    ActorExistenceCondition,
    AlwaysTrueCondition,
    AndCondition,
    BaseCondition,
    CollisionCondition,
    ComparisonRule,
    ElapsedTimeCondition,
    EntityInAreaCondition,
    EntityLanePositionCondition,
    OrCondition,
    ScenarioResult,
    SpeedCondition,
    SpeedCoordinateSystem,
    SpeedDirection,
    StandstillCondition,
    StickyCondition,
    TimeoutCondition,
    find_actor_by_role_name,
)
from .constants import EGO_ROLE_NAME
from .coordinate import (
    CarlaWorldPose,
    CoordinateFrame,
    FrameMismatchError,
    Lanelet2Pose,
    MapManager,
    OpenDrivePose,
    frame_of,
    snap_to_carla_road,
    to_carla_location,
    to_carla_world,
    to_lanelet2,
    to_opendrive,
)
from .entity import (
    EgoVehicle,
    SpawnLocation,
    SpawnPointIndex,
    SpawnTransform,
    VehicleEntity,
    VehicleEntityConfig,
)
from .kinematics import (
    AbsoluteAcceleration,
    AbsoluteVelocity,
    FrenetAcceleration,
    FrenetVelocity,
    RelativeAcceleration,
    RelativeVelocity,
    Vector3,
)
from .pytest_fixtures import CarlaScenarioFixture
from .scenario_base import BaseScenario, EgoConfig
from .scenario_queue import ScenarioQueue
from .server import CarlaServerManager
from .utils import (
    find_nearest_traffic_light,
    lanelet2_traffic_light_id_to_opendrive_controller_id,
    set_all_traffic_lights_state,
    set_group_traffic_light_state,
)

__all__ = [
    "EGO_ROLE_NAME",
    "ScenarioRunner",
    "CarlaScenarioFixture",
    "CarlaServerManager",
    "ActorExistenceCondition",
    "AlwaysTrueCondition",
    "AndCondition",
    "BaseCondition",
    "BaseScenario",
    "CarlaWorldPose",
    "CollisionCondition",
    "ComparisonRule",
    "ElapsedTimeCondition",
    "EntityInAreaCondition",
    "EntityLanePositionCondition",
    "OrCondition",
    "SpeedCondition",
    "SpeedCoordinateSystem",
    "SpeedDirection",
    "StandstillCondition",
    "StickyCondition",
    "EgoConfig",
    "EgoVehicle",
    "SpawnLocation",
    "SpawnPointIndex",
    "SpawnTransform",
    "VehicleEntity",
    "VehicleEntityConfig",
    "Lanelet2Pose",
    "MapManager",
    "OpenDrivePose",
    "ScenarioQueue",
    "ScenarioResult",
    "TimeoutCondition",
    "to_carla_location",
    "to_carla_world",
    "to_lanelet2",
    "to_opendrive",
    "find_nearest_traffic_light",
    "frame_of",
    "snap_to_carla_road",
    "lanelet2_traffic_light_id_to_opendrive_controller_id",
    "find_actor_by_role_name",
    "set_all_traffic_lights_state",
    "set_group_traffic_light_state",
    # Kinematics
    "CoordinateFrame",
    "FrameMismatchError",
    "Vector3",
    "AbsoluteVelocity",
    "RelativeVelocity",
    "FrenetVelocity",
    "AbsoluteAcceleration",
    "RelativeAcceleration",
    "FrenetAcceleration",
    # Actions
    "BaseAction",
    "TickTiming",
    "TurnAction",
    "TurnDirection",
]
