"""OpenDRIVE root element and export functionality."""

import importlib.metadata
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Union

import lxml.etree as ET

from .header import Header
from .junction import Junction
from .road import Road
from .signal import Controller


@dataclass
class OpenDRIVE:
    """Root OpenDRIVE element."""

    header: Optional[Header] = None
    roads: Optional[List[Road]] = None
    junctions: Optional[List[Junction]] = None
    controllers: Optional[List[Controller]] = None

    def __post_init__(self) -> None:
        if self.roads is None:
            self.roads = []
        if self.junctions is None:
            self.junctions = []
        if self.controllers is None:
            self.controllers = []

    def to_xml(self) -> ET.Element:
        """Convert to XML element."""
        elem = ET.Element("OpenDRIVE")

        if self.header:
            elem.append(self.header.to_xml())

        if self.roads:
            for road in self.roads:
                elem.append(road.to_xml())

        if self.controllers:
            for controller in self.controllers:
                elem.append(controller.to_xml())

        if self.junctions:
            for junction in self.junctions:
                elem.append(junction.to_xml())

        return elem


# Export functionality


def get_version_string() -> str:
    """
    Get version string from git, falling back to package version.

    Returns version in the format:
    - "v1.9.0" if on a tagged commit
    - "v1.8.5-abc1234" if on an untagged commit (nearest tag + commit hash)
    - "vX.Y.Z" from package metadata if git is unavailable

    Returns:
        Version string
    """
    # Try to get exact tag for current commit
    try:
        result = subprocess.run(
            ["git", "describe", "--tags", "--exact-match"],
            capture_output=True,
            text=True,
            check=True,
            timeout=5,
        )
        return result.stdout.strip()  # e.g. "v1.9.0"
    except (
        subprocess.CalledProcessError,
        subprocess.TimeoutExpired,
        FileNotFoundError,
    ):
        pass

    # Try to get nearest tag + commit hash
    try:
        tag_result = subprocess.run(
            ["git", "describe", "--tags", "--abbrev=0"],
            capture_output=True,
            text=True,
            check=True,
            timeout=5,
        )
        hash_result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
            timeout=5,
        )
        tag = tag_result.stdout.strip()  # e.g. "v1.8.5"
        commit = hash_result.stdout.strip()  # e.g. "abc1234"
        return f"{tag}-{commit}"  # e.g. "v1.8.5-abc1234"
    except (
        subprocess.CalledProcessError,
        subprocess.TimeoutExpired,
        FileNotFoundError,
    ):
        pass

    # Fallback to package metadata
    try:
        pkg_version = importlib.metadata.version("autoware-lanelet2-to-opendrive")
        return f"v{pkg_version}"
    except importlib.metadata.PackageNotFoundError:
        return "unknown"


def export_to_xml(opendrive: OpenDRIVE) -> str:
    """
    Export OpenDRIVE object to XML string with version comment.

    Args:
        opendrive: OpenDRIVE object to export

    Returns:
        XML string representation with version comment
    """
    xml_element = opendrive.to_xml()

    # Get version string (from git or package metadata)
    version = get_version_string()

    # Create version comment
    comment_text = f" Generated by autoware_lanelet2_to_opendrive {version} "
    version_comment = ET.Comment(comment_text)

    # Insert comment before root element
    xml_element.addprevious(version_comment)

    # Pretty print
    xml_str = ET.tostring(
        xml_element.getroottree(),
        pretty_print=True,
        xml_declaration=True,
        encoding="UTF-8",
    ).decode("utf-8")

    return xml_str


def save_opendrive_to_file(opendrive: OpenDRIVE, filepath: Union[str, Path]) -> None:
    """
    Save OpenDRIVE object to XML file.

    Args:
        opendrive: OpenDRIVE object to save
        filepath: Path to save the XML file
    """
    xml_str = export_to_xml(opendrive)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(xml_str)
