"""OpenDRIVE root element and export functionality."""

from dataclasses import dataclass
from typing import Optional, List, Union
import importlib.metadata
import lxml.etree as ET

from .header import Header
from .road import Road
from .junction import Junction
from .signal import Controller

from pathlib import Path


@dataclass
class OpenDRIVE:
    """Root OpenDRIVE element."""

    header: Optional[Header] = None
    roads: Optional[List[Road]] = None
    junctions: Optional[List[Junction]] = None
    controllers: Optional[List[Controller]] = None

    def __post_init__(self) -> None:
        if self.roads is None:
            self.roads = []
        if self.junctions is None:
            self.junctions = []
        if self.controllers is None:
            self.controllers = []

    def to_xml(self) -> ET.Element:
        """Convert to XML element."""
        elem = ET.Element("OpenDRIVE")

        if self.header:
            elem.append(self.header.to_xml())

        if self.roads:
            for road in self.roads:
                elem.append(road.to_xml())

        if self.controllers:
            for controller in self.controllers:
                elem.append(controller.to_xml())

        if self.junctions:
            for junction in self.junctions:
                elem.append(junction.to_xml())

        return elem


# Export functionality


def export_to_xml(opendrive: OpenDRIVE) -> str:
    """
    Export OpenDRIVE object to XML string with version comment.

    Args:
        opendrive: OpenDRIVE object to export

    Returns:
        XML string representation with version comment
    """
    xml_element = opendrive.to_xml()

    # Get package version
    try:
        version = importlib.metadata.version("autoware-lanelet2-to-opendrive")
    except importlib.metadata.PackageNotFoundError:
        version = "unknown"

    # Create version comment
    comment_text = f" Generated by autoware_lanelet2_to_opendrive v{version} "
    version_comment = ET.Comment(comment_text)

    # Insert comment before root element
    xml_element.addprevious(version_comment)

    # Pretty print
    xml_str = ET.tostring(
        xml_element.getroottree(),
        pretty_print=True,
        xml_declaration=True,
        encoding="UTF-8",
    ).decode("utf-8")

    return xml_str


def save_opendrive_to_file(opendrive: OpenDRIVE, filepath: Union[str, Path]) -> None:
    """
    Save OpenDRIVE object to XML file.

    Args:
        opendrive: OpenDRIVE object to save
        filepath: Path to save the XML file
    """
    xml_str = export_to_xml(opendrive)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(xml_str)
